language: cpp
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc-4.8.1
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_C_COMPILER=gcc-4.8 ../
        - make -j 2
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - xorg-dev
            - libglu1-mesa-dev
            - g++-4.8
            - cmake
            - cmake-data
    - os: osx
      compiler: clang
      script:
        - mkdir build
        - cd build
        - cmake ../
        - make -j 2
